// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ContainerLogger is an autogenerated mock type for the Logger type
type ContainerLogger struct {
	mock.Mock
}

type ContainerLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *ContainerLogger) EXPECT() *ContainerLogger_Expecter {
	return &ContainerLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: _a0, _a1
func (_m *ContainerLogger) Debug(_a0 string, _a1 ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	_m.Called(_ca...)
}

// ContainerLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type ContainerLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - _a0 string
//   - _a1 ...interface{}
func (_e *ContainerLogger_Expecter) Debug(_a0 interface{}, _a1 ...interface{}) *ContainerLogger_Debug_Call {
	return &ContainerLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *ContainerLogger_Debug_Call) Run(run func(_a0 string, _a1 ...interface{})) *ContainerLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ContainerLogger_Debug_Call) Return() *ContainerLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *ContainerLogger_Debug_Call) RunAndReturn(run func(string, ...interface{})) *ContainerLogger_Debug_Call {
	_c.Call.Return(run)
	return _c
}

// Warn provides a mock function with given fields: _a0, _a1
func (_m *ContainerLogger) Warn(_a0 string, _a1 ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	_m.Called(_ca...)
}

// ContainerLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type ContainerLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - _a0 string
//   - _a1 ...interface{}
func (_e *ContainerLogger_Expecter) Warn(_a0 interface{}, _a1 ...interface{}) *ContainerLogger_Warn_Call {
	return &ContainerLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *ContainerLogger_Warn_Call) Run(run func(_a0 string, _a1 ...interface{})) *ContainerLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ContainerLogger_Warn_Call) Return() *ContainerLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *ContainerLogger_Warn_Call) RunAndReturn(run func(string, ...interface{})) *ContainerLogger_Warn_Call {
	_c.Call.Return(run)
	return _c
}

// NewContainerLogger creates a new instance of ContainerLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainerLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainerLogger {
	mock := &ContainerLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
