// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ContainerMemory is an autogenerated mock type for the Memory type
type ContainerMemory struct {
	mock.Mock
}

type ContainerMemory_Expecter struct {
	mock *mock.Mock
}

func (_m *ContainerMemory) EXPECT() *ContainerMemory_Expecter {
	return &ContainerMemory_Expecter{mock: &_m.Mock}
}

// AddID provides a mock function with given fields: _a0
func (_m *ContainerMemory) AddID(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AddID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerMemory_AddID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddID'
type ContainerMemory_AddID_Call struct {
	*mock.Call
}

// AddID is a helper method to define mock.On call
//   - _a0 string
func (_e *ContainerMemory_Expecter) AddID(_a0 interface{}) *ContainerMemory_AddID_Call {
	return &ContainerMemory_AddID_Call{Call: _e.mock.On("AddID", _a0)}
}

func (_c *ContainerMemory_AddID_Call) Run(run func(_a0 string)) *ContainerMemory_AddID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ContainerMemory_AddID_Call) Return(_a0 error) *ContainerMemory_AddID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerMemory_AddID_Call) RunAndReturn(run func(string) error) *ContainerMemory_AddID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveID provides a mock function with given fields: _a0
func (_m *ContainerMemory) RemoveID(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RemoveID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerMemory_RemoveID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveID'
type ContainerMemory_RemoveID_Call struct {
	*mock.Call
}

// RemoveID is a helper method to define mock.On call
//   - _a0 string
func (_e *ContainerMemory_Expecter) RemoveID(_a0 interface{}) *ContainerMemory_RemoveID_Call {
	return &ContainerMemory_RemoveID_Call{Call: _e.mock.On("RemoveID", _a0)}
}

func (_c *ContainerMemory_RemoveID_Call) Run(run func(_a0 string)) *ContainerMemory_RemoveID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ContainerMemory_RemoveID_Call) Return(_a0 error) *ContainerMemory_RemoveID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerMemory_RemoveID_Call) RunAndReturn(run func(string) error) *ContainerMemory_RemoveID_Call {
	_c.Call.Return(run)
	return _c
}

// NewContainerMemory creates a new instance of ContainerMemory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainerMemory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainerMemory {
	mock := &ContainerMemory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
