// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	context "context"

	container "github.com/blocky/compiler/internal/container"

	mock "github.com/stretchr/testify/mock"
)

// ContainerClient is an autogenerated mock type for the Client type
type ContainerClient struct {
	mock.Mock
}

type ContainerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ContainerClient) EXPECT() *ContainerClient_Expecter {
	return &ContainerClient_Expecter{mock: &_m.Mock}
}

// Compatible provides a mock function with given fields: _a0
func (_m *ContainerClient) Compatible(_a0 context.Context) (bool, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Compatible")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerClient_Compatible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compatible'
type ContainerClient_Compatible_Call struct {
	*mock.Call
}

// Compatible is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *ContainerClient_Expecter) Compatible(_a0 interface{}) *ContainerClient_Compatible_Call {
	return &ContainerClient_Compatible_Call{Call: _e.mock.On("Compatible", _a0)}
}

func (_c *ContainerClient_Compatible_Call) Run(run func(_a0 context.Context)) *ContainerClient_Compatible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ContainerClient_Compatible_Call) Return(_a0 bool, _a1 error) *ContainerClient_Compatible_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContainerClient_Compatible_Call) RunAndReturn(run func(context.Context) (bool, error)) *ContainerClient_Compatible_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *ContainerClient) Create(_a0 context.Context, _a1 container.Config) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, container.Config) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, container.Config) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, container.Config) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ContainerClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 container.Config
func (_e *ContainerClient_Expecter) Create(_a0 interface{}, _a1 interface{}) *ContainerClient_Create_Call {
	return &ContainerClient_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *ContainerClient_Create_Call) Run(run func(_a0 context.Context, _a1 container.Config)) *ContainerClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(container.Config))
	})
	return _c
}

func (_c *ContainerClient_Create_Call) Return(_a0 string, _a1 error) *ContainerClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContainerClient_Create_Call) RunAndReturn(run func(context.Context, container.Config) (string, error)) *ContainerClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ImageExists provides a mock function with given fields: _a0, _a1
func (_m *ContainerClient) ImageExists(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ImageExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContainerClient_ImageExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageExists'
type ContainerClient_ImageExists_Call struct {
	*mock.Call
}

// ImageExists is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ContainerClient_Expecter) ImageExists(_a0 interface{}, _a1 interface{}) *ContainerClient_ImageExists_Call {
	return &ContainerClient_ImageExists_Call{Call: _e.mock.On("ImageExists", _a0, _a1)}
}

func (_c *ContainerClient_ImageExists_Call) Run(run func(_a0 context.Context, _a1 string)) *ContainerClient_ImageExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ContainerClient_ImageExists_Call) Return(_a0 bool, _a1 error) *ContainerClient_ImageExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContainerClient_ImageExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *ContainerClient_ImageExists_Call {
	_c.Call.Return(run)
	return _c
}

// Logs provides a mock function with given fields: _a0, _a1
func (_m *ContainerClient) Logs(_a0 context.Context, _a1 string) (string, string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Logs")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ContainerClient_Logs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logs'
type ContainerClient_Logs_Call struct {
	*mock.Call
}

// Logs is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ContainerClient_Expecter) Logs(_a0 interface{}, _a1 interface{}) *ContainerClient_Logs_Call {
	return &ContainerClient_Logs_Call{Call: _e.mock.On("Logs", _a0, _a1)}
}

func (_c *ContainerClient_Logs_Call) Run(run func(_a0 context.Context, _a1 string)) *ContainerClient_Logs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ContainerClient_Logs_Call) Return(_a0 string, _a1 string, _a2 error) *ContainerClient_Logs_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ContainerClient_Logs_Call) RunAndReturn(run func(context.Context, string) (string, string, error)) *ContainerClient_Logs_Call {
	_c.Call.Return(run)
	return _c
}

// PullImage provides a mock function with given fields: _a0, _a1
func (_m *ContainerClient) PullImage(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PullImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerClient_PullImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullImage'
type ContainerClient_PullImage_Call struct {
	*mock.Call
}

// PullImage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ContainerClient_Expecter) PullImage(_a0 interface{}, _a1 interface{}) *ContainerClient_PullImage_Call {
	return &ContainerClient_PullImage_Call{Call: _e.mock.On("PullImage", _a0, _a1)}
}

func (_c *ContainerClient_PullImage_Call) Run(run func(_a0 context.Context, _a1 string)) *ContainerClient_PullImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ContainerClient_PullImage_Call) Return(_a0 error) *ContainerClient_PullImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerClient_PullImage_Call) RunAndReturn(run func(context.Context, string) error) *ContainerClient_PullImage_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: _a0, _a1
func (_m *ContainerClient) Remove(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerClient_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type ContainerClient_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ContainerClient_Expecter) Remove(_a0 interface{}, _a1 interface{}) *ContainerClient_Remove_Call {
	return &ContainerClient_Remove_Call{Call: _e.mock.On("Remove", _a0, _a1)}
}

func (_c *ContainerClient_Remove_Call) Run(run func(_a0 context.Context, _a1 string)) *ContainerClient_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ContainerClient_Remove_Call) Return(_a0 error) *ContainerClient_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerClient_Remove_Call) RunAndReturn(run func(context.Context, string) error) *ContainerClient_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: _a0, _a1
func (_m *ContainerClient) Start(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ContainerClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ContainerClient_Expecter) Start(_a0 interface{}, _a1 interface{}) *ContainerClient_Start_Call {
	return &ContainerClient_Start_Call{Call: _e.mock.On("Start", _a0, _a1)}
}

func (_c *ContainerClient_Start_Call) Run(run func(_a0 context.Context, _a1 string)) *ContainerClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ContainerClient_Start_Call) Return(_a0 error) *ContainerClient_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerClient_Start_Call) RunAndReturn(run func(context.Context, string) error) *ContainerClient_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: _a0, _a1
func (_m *ContainerClient) Stop(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContainerClient_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type ContainerClient_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ContainerClient_Expecter) Stop(_a0 interface{}, _a1 interface{}) *ContainerClient_Stop_Call {
	return &ContainerClient_Stop_Call{Call: _e.mock.On("Stop", _a0, _a1)}
}

func (_c *ContainerClient_Stop_Call) Run(run func(_a0 context.Context, _a1 string)) *ContainerClient_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ContainerClient_Stop_Call) Return(_a0 error) *ContainerClient_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContainerClient_Stop_Call) RunAndReturn(run func(context.Context, string) error) *ContainerClient_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with given fields: _a0, _a1
func (_m *ContainerClient) Wait(_a0 context.Context, _a1 string) (int, string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 int
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ContainerClient_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type ContainerClient_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ContainerClient_Expecter) Wait(_a0 interface{}, _a1 interface{}) *ContainerClient_Wait_Call {
	return &ContainerClient_Wait_Call{Call: _e.mock.On("Wait", _a0, _a1)}
}

func (_c *ContainerClient_Wait_Call) Run(run func(_a0 context.Context, _a1 string)) *ContainerClient_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ContainerClient_Wait_Call) Return(_a0 int, _a1 string, _a2 error) *ContainerClient_Wait_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ContainerClient_Wait_Call) RunAndReturn(run func(context.Context, string) (int, string, error)) *ContainerClient_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewContainerClient creates a new instance of ContainerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainerClient {
	mock := &ContainerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
