// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StateCleaner is an autogenerated mock type for the Cleaner type
type StateCleaner struct {
	mock.Mock
}

type StateCleaner_Expecter struct {
	mock *mock.Mock
}

func (_m *StateCleaner) EXPECT() *StateCleaner_Expecter {
	return &StateCleaner_Expecter{mock: &_m.Mock}
}

// CleanUp provides a mock function with given fields: _a0, _a1
func (_m *StateCleaner) CleanUp(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CleanUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StateCleaner_CleanUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanUp'
type StateCleaner_CleanUp_Call struct {
	*mock.Call
}

// CleanUp is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *StateCleaner_Expecter) CleanUp(_a0 interface{}, _a1 interface{}) *StateCleaner_CleanUp_Call {
	return &StateCleaner_CleanUp_Call{Call: _e.mock.On("CleanUp", _a0, _a1)}
}

func (_c *StateCleaner_CleanUp_Call) Run(run func(_a0 context.Context, _a1 string)) *StateCleaner_CleanUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StateCleaner_CleanUp_Call) Return(_a0 error) *StateCleaner_CleanUp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StateCleaner_CleanUp_Call) RunAndReturn(run func(context.Context, string) error) *StateCleaner_CleanUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewStateCleaner creates a new instance of StateCleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateCleaner(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateCleaner {
	mock := &StateCleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
