name: Setup Environment
description: 'Setup Environment for workflows'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
