name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  unit-test:
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Run Unit Tests
        run: make test-short

  integration-test:
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/blocky/*
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Setup docker buildx
        shell: bash
        run: |
          make container-setup

      - name: Run Integration Tests
        run: make test-integration-dind

  compatibility-test:
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/blocky/*
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Setup docker buildx
        shell: bash
        run: |
          make container-setup

      - name: Run Compatibility Tests
        run: make test-compatibility-dind

  release:
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/blocky/*
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Make Release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
